services:
  # Cleaner Service (Y-axis)
  cleaner-service:
    build:
      context: .
      dockerfile: EnronEmailSearch/Indexer/Dockerfile
      args:
        - SERVICE_TYPE=cleaner
    volumes:
      - ./enron_dataset:/app/enron_dataset
      - ./cleaned_emails:/app/cleaned_emails
    command: --clean-only --input /app/enron_dataset --output /app/cleaned_emails
    environment:
      - SERVICE_TYPE=cleaner
    restart: "no"  # Run once and exit
  
  # Indexer Service (Y-axis)
  indexer-service:
    build:
      context: .
      dockerfile: EnronEmailSearch/Indexer/Dockerfile
      args:
        - SERVICE_TYPE=indexer
    volumes:
      - ./cleaned_emails:/app/cleaned_emails
      - ./db:/app/db
    command: --index-only --output /app/cleaned_emails --db /app/db/enron_index.db
    environment:
      - SERVICE_TYPE=indexer
    depends_on:
      - cleaner-service
    restart: "no"  # Run once and exit
  
  # Search API Service (Y-axis)
  search-api:
    build:
      context: .
      dockerfile: EnronEmailSearch/Web/Dockerfile
      args:
        - SERVICE_TYPE=api
    ports:
      - "5001:80"
    volumes:
      - ./db:/app/db
    environment:
      - ServiceType=api
      - ConnectionStrings__DefaultConnection=Data Source=/app/db/enron_index.db
    depends_on:
      - indexer-service
    restart: always
  
  # Web UI Service (Y-axis)
  web-ui:
    build:
      context: .
      dockerfile: EnronEmailSearch/Web/Dockerfile
      args:
        - SERVICE_TYPE=ui
    ports:
      - "5000:80"
    environment:
      - ServiceType=ui
      - ApiUrl=http://search-api
    depends_on:
      - search-api
    restart: always
  
  # Load balancer remains the same
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-ui
    restart: always